/**
 * summarize-for-zentropy Prompt (Section 5.1)
 *
 * Static prompt template that formats conversation context
 * into a Zentropy Rolling Summary format.
 */

export const SUMMARIZE_FOR_ZENTROPY_NAME = "summarize-for-zentropy";

export const SUMMARIZE_FOR_ZENTROPY_DESCRIPTION =
  "將當前的對話上下文，整理成符合 Zentropy Rolling Summary 格式的精簡摘要。" +
  " Summarize the current conversation context into a concise Zentropy-style atomic note.";

export const SUMMARIZE_FOR_ZENTROPY_TEMPLATE = `請將以下內容總結為 Zentropy 風格的原子筆記：

1. **識別核心 Entity (Product)**：找出這段對話涉及的主要產品或專案。
2. **提取關鍵決策 (Key Decisions)**：列出所有重要的決策點與結論。
3. **忽略閒聊與冗餘**：去除不影響理解的對話內容。
4. **使用 Markdown 格式**：

## [Product Name] - [Topic]

### 關鍵決策
- 決策 1: ...
- 決策 2: ...

### 下一步行動
- [ ] Action 1
- [ ] Action 2

### 背景脈絡
簡述相關背景...

---
*Generated by Zentropy MCP Server*`;

export function getSummarizePrompt(): {
  name: string;
  description: string;
  arguments: Array<{
    name: string;
    description: string;
    required: boolean;
  }>;
} {
  return {
    name: SUMMARIZE_FOR_ZENTROPY_NAME,
    description: SUMMARIZE_FOR_ZENTROPY_DESCRIPTION,
    arguments: [
      {
        name: "context",
        description:
          "The conversation context or content to summarize into Zentropy format.",
        required: true,
      },
    ],
  };
}

export function renderSummarizePrompt(context: string): {
  role: "user";
  content: { type: "text"; text: string };
} {
  return {
    role: "user",
    content: {
      type: "text",
      text: `${SUMMARIZE_FOR_ZENTROPY_TEMPLATE}\n\n---\n\n以下是需要整理的內容：\n\n${context}`,
    },
  };
}
