// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFkEOGt_6T97Hmde9dcy_74y-SfGgUERQ',
    appId: '1:894512935237:android:6f16a7c05c560e8df88e2c',
    messagingSenderId: '894512935237',
    projectId: 'zentropy-4f7a5',
    storageBucket: 'zentropy-4f7a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhfjUUC9BPFiAPDVI2pVExtukJNYgagls',
    appId: '1:894512935237:ios:1de676e4d5f8b0d9f88e2c',
    messagingSenderId: '894512935237',
    projectId: 'zentropy-4f7a5',
    storageBucket: 'zentropy-4f7a5.firebasestorage.app',
    iosClientId: '894512935237-b6fqaj1t9rn8j058piao1v0cal5gko7k.apps.googleusercontent.com',
    iosBundleId: 'com.zentropy.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_API_KEY',
    appId: '1:894512935237:web:2533f9a2e7d09321f88e2c',
    messagingSenderId: '894512935237',
    projectId: 'zentropy-4f7a5',
    authDomain: 'zentropy-4f7a5.firebaseapp.com',
    storageBucket: 'zentropy-4f7a5.firebasestorage.app',
    measurementId: 'G-BHKRHNW4VH',
  );

}