version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: naruvia_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=naruvia
      - POSTGRES_PASSWORD=naruvia_password
      - POSTGRES_DB=naruvia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U naruvia -d naruvia_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
