/**
 * generate-spec-structure Prompt (Section 5.2)
 *
 * Static prompt template that generates a standard
 * Zentropy Specification document structure.
 */

export const GENERATE_SPEC_NAME = "generate-spec-structure";

export const GENERATE_SPEC_TEMPLATE = `請根據以下主題，生成一份符合 Zentropy 規格的 Specification 文件結構：

# [Specification Title]

**版本**: v1.0
**建立日期**: [DATE]
**狀態**: Draft

---

## 1. 概述 (Overview)
簡要描述此規格的目的與範圍。

## 2. 業務目標 (Business Objectives)
- 目標 1: ...
- 目標 2: ...

## 3. 功能需求 (Functional Requirements)

### 3.1 [Feature 1]
- **描述**: ...
- **輸入**: ...
- **輸出**: ...
- **驗收條件**: ...

### 3.2 [Feature 2]
- **描述**: ...
- **輸入**: ...
- **輸出**: ...
- **驗收條件**: ...

## 4. 非功能需求 (Non-Functional Requirements)
- **效能**: ...
- **安全性**: ...
- **可用性**: ...

## 5. 資料模型 (Data Model)
描述核心資料結構與關聯。

## 6. API 規格 (API Specification)
定義相關 API endpoints。

## 7. 約束與假設 (Constraints & Assumptions)
- 約束 1: ...
- 假設 1: ...

## 8. 附錄 (Appendix)
相關參考文件與連結。

---
*Generated by Zentropy MCP Server*`;

export function renderGenerateSpecPrompt(
  topic: string,
  productName?: string,
): {
  role: "user";
  content: { type: "text"; text: string };
} {
  const productContext = productName
    ? `\n\n此規格屬於產品：**${productName}**`
    : "";

  return {
    role: "user",
    content: {
      type: "text",
      text: `${GENERATE_SPEC_TEMPLATE}\n\n---\n\n主題：${topic}${productContext}`,
    },
  };
}
