"""Add task references field

Revision ID: 10f3d93bc551
Revises: 539ce44ec733
Create Date: 2026-01-26 15:51:41.044398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f3d93bc551'
down_revision: Union[str, Sequence[str], None] = '539ce44ec733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 只增加 references 欄位
    op.add_column('tasks', sa.Column('references', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除 references 欄位
    op.drop_column('tasks', 'references')
    # ### end Alembic commands ###
