"""add_milestone_and_task_time_fields

Revision ID: 1ec2de03811f
Revises: 6491912acd13
Create Date: 2026-01-24 23:36:18.114781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ec2de03811f'
down_revision: Union[str, Sequence[str], None] = '6491912acd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping _prisma_migrations if it doesn't exist
    # op.drop_table('_prisma_migrations')

    # Skip enum alteration as milestones table already has correct enum type
    # The milestones table should already exist from previous migrations

    # Add new time-related columns to tasks
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('inferred_from_milestone_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('time_confidence', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('urgency_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='urgencylevelenum'), nullable=True))

    op.create_foreign_key('fk_tasks_milestone', 'tasks', 'milestones', ['inferred_from_milestone_id'], ['id'])

    # Drop old column if it exists
    # op.drop_column('tasks', 'inferred_from_milestone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore old column if needed
    # op.add_column('tasks', sa.Column('inferred_from_milestone', sa.UUID(), autoincrement=False, nullable=True))

    op.drop_constraint('fk_tasks_milestone', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'urgency_level')
    op.drop_column('tasks', 'time_confidence')
    op.drop_column('tasks', 'inferred_from_milestone_id')
    op.drop_column('tasks', 'due_date')

    # Skip milestone table modifications as it already exists
    # Skip recreating _prisma_migrations
    # op.create_table('_prisma_migrations', ...)
    # ### end Alembic commands ###
