import { PrismaClient } from '@prisma/client';
import { google } from '@ai-sdk/google';
import { generateText } from 'ai';

const prisma = new PrismaClient();
const USER_ID = '467c7125-d890-429f-b46f-168429b1907e';

async function autoGenerateDescriptions() {
  try {
    console.log('🤖 自動生成 Product 描述...\n');

    // 找出所有沒有描述的 Products
    const products = await prisma.product.findMany({
      where: {
        user_id: USER_ID,
        deleted_at: null,
        OR: [
          { description: null },
          { description: '' }
        ]
      },
      include: {
        tasks: {
          where: { deleted_at: null },
          select: { content: true },
          take: 10  // 取前 10 個任務作為參考
        }
      }
    });

    console.log(`找到 ${products.length} 個需要生成描述的 Products\n`);

    for (const product of products) {
      console.log(`📦 處理: ${product.name}`);

      if (product.tasks.length === 0) {
        console.log(`   ⏭️  跳過（沒有任務，無法生成描述）\n`);
        continue;
      }

      // 使用 AI 生成描述
      const taskContents = product.tasks.map(t => t.content).join('\n- ');

      const { text: description } = await generateText({
        model: google('gemini-2.5-flash-lite'),
        prompt: `根據以下任務內容，為專案「${product.name}」生成一句簡短的描述（最多 50 字）：

任務內容：
- ${taskContents}

要求：
1. 只回傳描述文字，不要任何前綴或解釋
2. 描述應該概括這個專案的核心目標或領域
3. 使用繁體中文
4. 不超過 50 個字

描述：`,
      });

      const cleanedDescription = description.trim();

      // 更新到資料庫
      await prisma.product.update({
        where: { id: product.id },
        data: { description: cleanedDescription }
      });

      console.log(`   ✅ 已生成: "${cleanedDescription}"\n`);

      // 避免 API rate limit
      await new Promise(resolve => setTimeout(resolve, 500));
    }

    console.log('✅ 所有描述生成完成！\n');

    // 顯示最終結果
    const allProducts = await prisma.product.findMany({
      where: { user_id: USER_ID, deleted_at: null },
      select: { name: true, description: true }
    });

    console.log('📊 最終結果：\n');
    allProducts.forEach(p => {
      console.log(`📦 ${p.name}`);
      console.log(`   ${p.description || '(無描述)'}\n`);
    });

  } catch (error) {
    console.error('❌ 生成失敗:', error);
  } finally {
    await prisma.$disconnect();
  }
}

autoGenerateDescriptions();
